require_relative 'commands/get_gid'
require_relative 'commands/is_group'
require_relative 'commands/get_group'
require_relative 'commands/create_group'
require_relative 'commands/update_group'
require_relative 'commands/delete_group'
